import React, { useEffect, useRef, useState } from "react";
import { XIcon, QuestionMarkCircleIcon } from "@heroicons/react/solid";
import Head from "next/head";
type registerProps = {
  show: boolean;
  setShow: (show: boolean) => void;
};
function Register(props: registerProps) {
  const [dateDay, setDateDay] = useState<Array<number>>([]);
  const [dateYear, setDateYear] = useState<Array<number>>([]);
  const [isCustom, setIsCustom] = useState(false);
  //   const [show, setShow] = React.useState(false);

  const fnameRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    for (let i = 1; i <= 31; i++) {
      setDateDay((prevD) => [...prevD, i]);
    }

    for (let i = 2022; i >= 1905; i--) {
      setDateYear((prevY) => [...prevY, i]);
    }

    if (fnameRef.current) {
      fnameRef.current.focus();
      fnameRef.current.addEventListener("focusin", () => {});
      fnameRef.current.addEventListener("focusout", () => {
        if (fnameRef.current?.value === "") {
        }
      });
    }
  }, []);
  return (
    <div
      style={{
        display: props.show ? "flex" : "none",
      }}
    >
      <Head>
        <title>Facebook -log in or signup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center mx-auto  w-[50%] justify-center">
        <div className="w-full fixed top-0 left-0 h-full">
          <div className="absolute z-10 top-[20%] left-[40%] bg-white  shadow-2xl rounded-xl p-2 h-auto w-[432px]">
            <div>
              <div className="flex items-start justify-between mb-2.5">
                <div>
                  <h1 className="text-3xl">Sign Up</h1>
                  <p className="text-base">It's quick and easy.</p>
                </div>

                <XIcon
                  className="h-5 w-5 cursor-pointer"
                  onClick={() => props.setShow(false)}
                />
              </div>

              <div className="w-full h-0.5 bg-fbgray"></div>

              <form action="#">
                <div className="mt-4 pb-2  w-full flex flex-col">
                  <div className="flex flex-col">
                    <div className="flex pb-2 items-center w-full gap-3">
                      <input
                        className=" w-full p-2 text-base outline-none border border-solid border-[#ccd0d5] rounded-md bg-[#f6f6f7]"
                        type="text"
                        placeholder="First Name"
                        required
                        ref={fnameRef}
                      />
                      <input
                        className=" w-full p-2 text-base outline-none border border-solid border-[#ccd0d5] rounded-md bg-[#f6f6f7]"
                        type="text"
                        placeholder="Surename"
                        required
                      />
                    </div>
                    <input
                      className=" w-full p-2 text-base outline-none border border-solid border-[#ccd0d5] rounded-md bg-[#f6f6f7] mb-2.5 text-[#1c1e21]"
                      type="text"
                      placeholder="Mobile Number or email address"
                      required
                    />
                    <input
                      className=" w-full p-2 text-base outline-none border border-solid border-[#ccd0d5] rounded-md bg-[#f6f6f7] mb-2.5 text-[#1c1e21]"
                      type="password"
                      placeholder="Password"
                      required
                    />
                  </div>

                  <div className="flex flex-col items-start justify-center w-full shadow-none">
                    <div className="flex flex-row items-center gap-1 text-[#606770] text-xs font-normal my-1">
                      <p className="text-blue">Date of birth</p>
                      <QuestionMarkCircleIcon className="h-4 w-4" />
                    </div>

                    <div className="flex space-x-1 items-start justify-center w-full shadow-none ">
                      <select
                        className="w-full h-10 outline-none border border-solid bg-white border-fbgray rounded text-base font-normal"
                        name="day"
                        id="day-date"
                        required
                      >
                        {dateDay.map((day, index) => (
                          <option value={day} key={index}>
                            {day}
                          </option>
                        ))}
                      </select>
                      <select
                        className="w-full h-10 outline-none border border-solid bg-white border-fbgray rounded text-base font-normal"
                        name="month"
                        id="month-date"
                      >
                        <option value="Jan">Jan</option>
                        <option value="Feb">Feb</option>
                        <option value="Mar">Mar</option>
                        <option value="Apr">Apr</option>
                        <option value="May">May</option>
                        <option value="Jun">Jun</option>
                        <option value="Jul">Jul</option>
                        <option value="Aug">Aug</option>
                        <option value="Sep">Sep</option>
                        <option value="Oct">Oct</option>
                        <option value="Nov">Nov</option>
                        <option value="Dec">Dec</option>
                      </select>
                      <select
                        className="w-full h-10 outline-none border border-solid bg-white border-fbgray rounded text-base font-normal"
                        name="year"
                        id="year-date"
                        required
                      >
                        {dateYear.map((year, index) => (
                          <option value={year} key={index}>
                            {year}
                          </option>
                        ))}
                      </select>
                    </div>

                    <div className="flex items-center gap-1 text-[#606770] text-xs font-normal my-1">
                      <p>Gender</p>
                      <QuestionMarkCircleIcon className="h-4 w-4" />
                    </div>

                    <div className="w-full flex items-center justify-between gap-2.5 mb-2">
                      <div className="flex items-center justify-between w-full border border-fbgray solid p-3 text-base rounded">
                        <label
                          className="texty-base font-normal whitespace-nowrap"
                          htmlFor="female"
                        >
                          Female
                        </label>
                        <input
                          type="radio"
                          name="gender"
                          value="Female"
                          id="female"
                          onChange={() => setIsCustom(false)}
                        ></input>
                      </div>

                      <div className="flex items-center justify-between w-full border border-fbgray solid p-3 text-base rounded">
                        <label
                          className="texty-base font-normal whitespace-nowrap"
                          htmlFor="male"
                        >
                          Male
                        </label>
                        <input
                          type="radio"
                          name="gender"
                          value="Male"
                          id="male"
                          onChange={() => setIsCustom(false)}
                        ></input>
                      </div>

                      <div className="flex items-center justify-between w-full border border-fbgray solid p-3 text-base rounded">
                        <label
                          className="texty-base font-normal whitespace-nowrap"
                          htmlFor="custom"
                        >
                          Custom
                        </label>
                        <input
                          type="radio"
                          name="gender"
                          value="Custom"
                          id="custom"
                          onChange={() => setIsCustom(true)}
                        ></input>
                      </div>
                    </div>

                    {isCustom ? (
                      <div className="mt-2 flex flex-col w-full">
                        <select
                          className="w-full h-9 outline-none border rounded  border-solid border-fbgray text-base font-normal"
                          name="select-pronoun"
                        >
                          <option value="default">Select your pronoun</option>
                          <option value="She">She</option>
                          <option value="They">He</option>
                          <option value="They">They</option>
                        </select>
                        <p className="text-xs font-normal mb-1">
                          Your pronoun is visible to everyone.
                        </p>
                        <input
                          className="w-full p-3 text-base outline-none border border-solid border-[#ccd0d5] rounded bg-[#f5f6f7] mb-2.5 text-fbgray "
                          type="text"
                          placeholder="Gener (optional)"
                          required
                        />
                      </div>
                    ) : null}
                  </div>

                  <div className="flex flex-col items-center gap-2.5 text-[#777] text-xs mb-4 mt-0.5">
                    <p>
                      People who use our service may have uploaded your contact
                      information to Facebook.{" "}
                      <a className="text-[#385898] hover:underline" href="#">
                        Learn more.
                      </a>
                    </p>
                    <p>
                      By clicking Sign Up, you agree to our{" "}
                      <a className="text-[#385898] hover:underline" href="#">
                        Terms, Data Policy
                      </a>{" "}
                      and{" "}
                      <a className="text-[#385898] hover:underline" href="#">
                        Cookie Policy
                      </a>
                      . You may receive SMS notifications from us and can opt
                      out at any time.
                    </p>
                  </div>

                  <button
                    className="w-1/2  mx-auto h-9 border-none bg-[#00a400] rounded-md text-lg text-white overflow-hidden px-8 font-semibold"
                    type="submit"
                    id="signup-btn"
                  >
                    Sign Up
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Register;
